name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # my-blog 레포지토리의 main 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 필요한 Node.js 버전

      - name: Install dependencies
        run: yarn install

      - name: Build and Delpoy
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Personal Access Token
        run: |
          yarn build
          touch out/.nojekyll
          npx gh-pages -d out